const API_IMAGE_MAX_BASE64_SIZE = 5 * 1024 * 1024;

const IMAGE_TARGET_RAW_SIZE = (API_IMAGE_MAX_BASE64_SIZE * 3) / 4;

const IMAGE_MAX_WIDTH = 2000;
const IMAGE_MAX_HEIGHT = 2000;

const PDF_TARGET_RAW_SIZE = 20 * 1024 * 1024;

const API_PDF_MAX_PAGES = 100;

const PDF_EXTRACT_SIZE_THRESHOLD = 3 * 1024 * 1024;

const PDF_MAX_EXTRACT_SIZE = 100 * 1024 * 1024;

const PDF_MAX_PAGES_PER_READ = 20;

const PDF_AT_MENTION_INLINE_THRESHOLD = 10;

const API_MAX_MEDIA_PER_REQUEST = 100;

const DEFAULT_MAX_RESULT_SIZE_CHARS = 50_000;

const MAX_TOOL_RESULT_TOKENS = 100_000;

const BYTES_PER_TOKEN = 4;

const MAX_TOOL_RESULT_BYTES = MAX_TOOL_RESULT_TOKENS * BYTES_PER_TOKEN;

const MAX_TOOL_RESULTS_PER_MESSAGE_CHARS = 200_000;

const TOOL_SUMMARY_MAX_LENGTH = 50;

module.exports = {
  API_IMAGE_MAX_BASE64_SIZE,
  IMAGE_TARGET_RAW_SIZE,
  IMAGE_MAX_WIDTH,
  IMAGE_MAX_HEIGHT,
  PDF_TARGET_RAW_SIZE,
  API_PDF_MAX_PAGES,
  PDF_EXTRACT_SIZE_THRESHOLD,
  PDF_MAX_EXTRACT_SIZE,
  PDF_MAX_PAGES_PER_READ,
  PDF_AT_MENTION_INLINE_THRESHOLD,
  API_MAX_MEDIA_PER_REQUEST,
  DEFAULT_MAX_RESULT_SIZE_CHARS,
  MAX_TOOL_RESULT_TOKENS,
  BYTES_PER_TOKEN,
  MAX_TOOL_RESULT_BYTES,
  MAX_TOOL_RESULTS_PER_MESSAGE_CHARS,
  TOOL_SUMMARY_MAX_LENGTH
};
