/**
 * presentation-builder — PPT 制作编排器
 *
 * 分析用户主题 → 推断风格 → 生成大纲 → 路由到 pptx_generate 或 html-presentation。
 *
 * 参考 DashiAI PPT Skill 的编排理念：
 *   1. 先问主题/页数/风格偏好（或自动推断）
 *   2. 生成结构化大纲
 *   3. 路由到具体引擎执行
 */

// eslint-disable-next-line no-unused-vars
const path = require('path');
// eslint-disable-next-line no-unused-vars
const fs = require('fs');

const DEFAULT_STYLES = [
  { id: 'corporate-clean', label: '商务蓝', desc: '产品介绍/企业汇报' },
  { id: 'tokyo-night', label: '科技暗色', desc: '技术方案/开发者大会' },
  { id: 'pitch-deck-vc', label: '路演风', desc: '数据报告/融资路演' },
  { id: 'nord', label: '北欧蓝', desc: '品牌故事/深度专题' },
  { id: 'academic-paper', label: '学术白', desc: '调研报告/白皮书' },
  { id: 'aurora', label: '极光', desc: '高密度数据展示' },
  { id: 'catppuccin-mocha', label: '炫彩紫绿', desc: 'AI/科技发布会' },
  { id: 'sunset-warm', label: '暖日落', desc: '高端发布/品牌提案' },
];

function inferStyle(topic) {
  const lower = (topic || '').toLowerCase();
  if (/技术|开发|编程|架构|代码|ai|人工智能|算法/i.test(lower)) return 'tokyo-night';
  if (/数据|报告|分析|研究|市场|调研/i.test(lower)) return 'pitch-deck-vc';
  if (/品牌|故事|人物|专访|公关|媒体/.test(lower)) return 'nord';
  if (/学术|论文|白皮书|研究/.test(lower)) return 'academic-paper';
  if (/金融|投资|财报|商业/.test(lower)) return 'pitch-deck-vc';
  if (/产品|发布|路演|创业|融资/.test(lower)) return 'corporate-clean';
  return 'pitch-deck-vc';
}

function generateOutline(topic, slideCount) {
  var count = slideCount || 8;
  var prefix = topic || '演示主题';
  var slides = [
    { type: 'title', title: prefix, subtitle: 'Generated by CrabPaw' },
  ];

  var sections = [
    { title: '背景与概述', bullets: ['行业背景', '当前挑战', '我们的目标', '项目范围'] },
    { title: '核心分析', bullets: ['关键数据总览', '趋势分析', '竞品对比', '核心发现'] },
    { title: '方案与策略', bullets: ['解决方案概览', '实施路径', '里程碑规划', '资源需求'] },
    { title: '成果与展望', bullets: ['预期成果', 'KPIs', '后续计划', '总结'] },
  ];

  for (var i = 0; i < Math.min(sections.length, count - 1); i++) {
    var sec = sections[i];
    slides.push({ type: 'content', title: sec.title, bullets: sec.bullets });
  }

  slides.push({ type: 'summary', title: '总结', points: ['已完成分析', '方案明确', '下一步行动计划已制定'], conclusion: prefix + ' — 谢谢' });
  return slides;
}

async function execute(params) {
  var topic = params.topic || '';
  var style = params.style || inferStyle(topic);
  var slideCount = params.slideCount || 8;

  if (!topic) {
    return {
      success: false,
      error: '请提供演示主题（topic）',
      hint: '例如：{ "topic": "2025年度技术总结", "style": "tokyo-night", "slideCount": 10 }',
      availableStyles: DEFAULT_STYLES,
    };
  }

  var slides = generateOutline(topic, slideCount);

  return {
    success: true,
    topic: topic,
    style: style,
    slideCount: slides.length,
    slides: slides,
    message: '大纲已生成，如需调整可直接修改 slides 数组后调用 pptx_generate（PPT）或 html-presentation（HTML 网页版）',
    nextSteps: [
      { tool: 'pptx_generate', params: { slides: slides, style: style, title: topic }, desc: '生成 PowerPoint 文件' },
      { tool: 'html-presentation', params: { topic: topic, slides: slides, style: style }, desc: '生成 HTML 网页演示' },
    ],
  };
}

module.exports = { execute, generateOutline, inferStyle };
